// Run once: node scripts/fetchTeams.js
// Fetches all college teams from ESPN's public API and writes src/data/teams.ts

import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const SPORTS = [
  { key: 'CFB',    path: 'football/college-football' },
  { key: 'CBB',    path: 'basketball/mens-college-basketball' },
  { key: 'WSOFTB', path: 'softball/college-softball' },
  { key: 'CBASE',  path: 'baseball/college-baseball' },
];

async function fetchTeams(sport) {
  const url = `https://site.api.espn.com/apis/site/v2/sports/${sport.path}/teams?limit=1000`;
  const res  = await fetch(url);
  const data = await res.json();
  const teams = data?.sports?.[0]?.leagues?.[0]?.teams ?? [];
  return teams.map(({ team }) => ({
    abbrev:     team.abbreviation?.toUpperCase(),
    name:       team.displayName,
    shortName:  team.shortDisplayName ?? team.displayName,
    id:         team.id,
    sport:      sport.key,
  })).filter(t => t.abbrev && t.id);
}

const all = {};
for (const sport of SPORTS) {
  console.log(`Fetching ${sport.key}...`);
  const teams = await fetchTeams(sport);
  console.log(`  ${teams.length} teams`);
  for (const t of teams) {
    const entry = { name: t.name, shortName: t.shortName, id: t.id };
    const shortKey = t.shortName.toUpperCase().replace(/\s+/g, '_');
    all[t.abbrev]              = all[t.abbrev] ?? entry;
    all[shortKey]              = all[shortKey] ?? entry;
    all[`${t.sport}:${t.abbrev}`]   = entry;
    all[`${t.sport}:${shortKey}`]   = entry;
  }
}

const out = `// Auto-generated by scripts/fetchTeams.js — do not edit manually
export interface TeamInfo { name: string; shortName: string; id: string; }

const TEAMS: Record<string, TeamInfo> = ${JSON.stringify(all, null, 2)};

export default TEAMS;

export function espnLogoUrl(id: string): string {
  return \`https://a.espncdn.com/i/teamlogos/ncaa/500/\${id}.png\`;
}
`;

const outPath = join(__dirname, '../src/data/teams.ts');
writeFileSync(outPath, out);
console.log(`\nWrote ${Object.keys(all).length} entries to src/data/teams.ts`);
